name: Show Changed Files in PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List changed files in the PR
        run: |
          echo "Files changed in this PR:"
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} > files.txt
          cat files.txt
